### ISSUE TITLE
Say doesn't support new lines

### ISSUE THREAD

**Issue by NyanSpaghetti** [Mikibot/MiScript#2]
Doing >createcommand test say "test
test"

Creates an error:
System.Exception: Expected var!
   at MiScript.Parser.Parser.Var(ParseContext context)
   at MiScript.Parser.Parser.Body(ParseContext context)
   at MiScript.Parser.Parser.Parse(Dictionary`2 contextVariables)
   at Miki.Modules.CustomCommands.CustomCommandsModule.NewCustomCommandAsync(ICommandContext e) in /home/vsts/work/1/s/Miki/Modules/CustomCommands/CustomCommandsModule.cs:line 74

**Comment by hello-o** [comment]
Damn it

**Comment by velddev** [comment]
Thanks for the issue report. Sorry for the late reply, but I've added it to the planning to allow for new lines to be more accessible.
